name: uchicago_lnm_project
channels:
  - plotly
  - defaults
dependencies:
  - python=3.10
  - tensorflow
  - absl-py
  - aiohttp
  - altair
  - astunparse
  - attrs
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - blas
  - blinker
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - comm
  - contourpy
  - cryptography
  - cycler
  - datasets
  - decorator
  - dill
  - exceptiongroup
  - executing
  - filelock
  - flatbuffers
  - fonttools
  - frozenlist
  - fsspec
  - future
  - gast
  - giflib
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - googleapis-common-protos
  - grpcio
  - h5py
  - hdf5
  - huggingface_hub
  - idna
  - imagecodecs
  - imageio
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_widgets
  - keras
  - keras-preprocessing
  - kiwisolver
  - lcms2
  - lerc
  - libaec
  - libavif
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcurl
  - libdeflate
  - libevent
  - libffi
  - libpng
  - libprotobuf
  - libsodium
  - libssh2
  - libtiff
  - libwebp-base
  - lime
  - llvmlite
  - lz4-c
  - markdown
  - markupsafe
  - mathjax
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mkl  # If issues arise on macOS, consider replacing this with `openblas`
  - mkl-service
  - mkl_fft
  - mkl_random
  - multidict
  - multiprocess
  - nbformat
  - nest-asyncio
  - networkx
  - nltk
  - numba
  - numexpr
  - numpy
  - oauthlib
  - openjpeg
  - openssl
  - opt_einsum
  - orc
  - packaging
  - pandas
  - parso
  - pillow
  - pip
  - platformdirs
  - plotly
  - plotly-orca
  - ply
  - promise
  - prompt-toolkit
  - protobuf
  - psutil
  - pure_eval
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pybind11-abi
  - pycparser
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python-dateutil
  - python-fastjsonschema
  - python-flatbuffers
  - python-kaleido
  - python-tzdata
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - re2
  - referencing
  - regex
  - requests
  - requests-oauthlib
  - responses
  - rpds-py
  - rsa
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - shap
  - sip
  - six
  - slicer
  - snappy
  - sqlite
  - stack_data
  - tbb
  - tenacity
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-datasets
  - tensorflow-estimator
  - tensorflow-metadata
  - termcolor
  - threadpoolctl
  - tifffile
  - tk
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - utf8proc
  - wcwidth
  - werkzeug
  - wheel
  - widgetsnbextension
  - wordcloud
  - wrapt
  - xz
  - yaml
  - yarl
  - zlib
  - zstd
